/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AToggle {
        "label": string;
        "type": string;
        "value": any;
    }
}
declare global {
    interface HTMLAToggleElement extends Components.AToggle, HTMLStencilElement {
    }
    var HTMLAToggleElement: {
        prototype: HTMLAToggleElement;
        new (): HTMLAToggleElement;
    };
    interface HTMLElementTagNameMap {
        "a-toggle": HTMLAToggleElement;
    }
}
declare namespace LocalJSX {
    interface AToggle {
        "label"?: string;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        "type"?: string;
        "value"?: any;
    }
    interface IntrinsicElements {
        "a-toggle": AToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-toggle": LocalJSX.AToggle & JSXBase.HTMLAttributes<HTMLAToggleElement>;
        }
    }
}
